<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Tlt.Core\Tlt.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
